<?php
/**
 * Created by PhpStorm.
 * User: qp
 * Date: 18.01.2018
 * Time: 16:07
 */

return [
    'sEcho' => 1,
    'iColumns' => 50,
    'sColumns',
    'iDisplayStart' => 0,
    'iDisplayLength' => 5000,
    'mDataProp_0' => 'id',
    'mDataProp_1' => 'terminal',
    'mDataProp_2' => 'status',
    'mDataProp_3' => 'managed',
    'mDataProp_4' => 'exclusive',
    'mDataProp_5' => 'shared',
    'mDataProp_6' => 'ref',
    'mDataProp_7' => 'unit',
    'mDataProp_8' => 'category_id',
    'mDataProp_9' => 'region_id',
    'mDataProp_10' => 'area_location_id',
    'mDataProp_11' => 'sub_area_location_id',
    'mDataProp_12' => 'beds',
    'mDataProp_13' => 'size',
    'mDataProp_14' => 'price',
    'mDataProp_15' => 'agent_id',
    'mDataProp_16' => 'landlord_id',
    'mDataProp_17' => 'owner_email',
    'mDataProp_18' => 'owner_mobile',
    'mDataProp_19' => 'unit_type',
    'mDataProp_20' => 'baths',
    'mDataProp_21' => 'street_no',
    'mDataProp_22' => 'floor_no',
    'mDataProp_23' => 'dewa_no',
    'mDataProp_24' => 'photos',
    'mDataProp_25' => 'cheques',
    'mDataProp_26' => 'fitted',
    'mDataProp_27' => 'prop_status',
    'mDataProp_28' => 'source_of_listing',
    'mDataProp_29' => 'available_date',
    'mDataProp_30' => 'remind_me',
    'mDataProp_31' => 'furnished',
    'mDataProp_32' => 'featured',
    'mDataProp_33' => 'maintenance',
    'mDataProp_34' => 'strno',
    'mDataProp_35' => 'amount',
    'mDataProp_36' => 'tenanted',
    'mDataProp_37' => 'plot_size',
    'mDataProp_38' => 'name',
    'mDataProp_39' => 'view_id',
    'mDataProp_40' => 'commission',
    'mDataProp_41' => 'deposit',
    'mDataProp_42' => 'unit_size_price',
    'mDataProp_43' => 'dateadded',
    'mDataProp_44' => 'dateupdated',
    'mDataProp_45' => 'user_id',
    'mDataProp_46' => 'key_location',
    'mDataProp_47' => 'development_unit_id',
    'mDataProp_48' => 'other_title_2',
    'mDataProp_49' => 'rera_permit',
    /*'sSearch' => false,
    'bRegex',
    'sSearch_0' => false,
    'bRegex_0',
    'bSearchable_0',
    'sSearch_1' => false,
    'bRegex_1',
    'bSearchable_1',
    'sSearch_2' => false,
    'bRegex_2',
    'bSearchable_2',
    'sSearch_3' => false,
    'bRegex_3',
    'bSearchable_3',
    'sSearch_4' => false,
    'bRegex_4',
    'bSearchable_4',
    'sSearch_5' => false,
    'bRegex_5',
    'bSearchable_5',
    'sSearch_6' => false,
    'bRegex_6',
    'bSearchable_6',
    'sSearch_7' => false,
    'bRegex_7',
    'bSearchable_7',
    'sSearch_8' => false,
    'bRegex_8',
    'bSearchable_8',
    'sSearch_9' => false,
    'bRegex_9',
    'bSearchable_9',
    'sSearch_10' => false,
    'bRegex_10',
    'bSearchable_10',
    'sSearch_11' => false,
    'bRegex_11',
    'bSearchable_11',
    'sSearch_12' => false,
    'bRegex_12',
    'bSearchable_12',
    'sSearch_13' => false,
    'bRegex_13',
    'bSearchable_13',
    'sSearch_14' => false,
    'bRegex_14',
    'bSearchable_14',
    'sSearch_15' => false,
    'bRegex_15',
    'bSearchable_15',
    'sSearch_16' => false,
    'bRegex_16',
    'bSearchable_16',
    'sSearch_17' => false,
    'bRegex_17',
    'bSearchable_17',
    'sSearch_18' => false,
    'bRegex_18',
    'bSearchable_18',
    'sSearch_19' => false,
    'bRegex_19',
    'bSearchable_19',
    'sSearch_20' => false,
    'bRegex_20',
    'bSearchable_20',
    'sSearch_21' => false,
    'bRegex_21',
    'bSearchable_21',
    'sSearch_22' => false,
    'bRegex_22',
    'bSearchable_22',
    'sSearch_23' => false,
    'bRegex_23',
    'bSearchable_23',
    'sSearch_24' => false,
    'bRegex_24',
    'bSearchable_24',
    'sSearch_25' => false,
    'bRegex_25',
    'bSearchable_25',
    'sSearch_26' => false,
    'bRegex_26',
    'bSearchable_26',
    'sSearch_27' => false,
    'bRegex_27',
    'bSearchable_27',
    'sSearch_28' => false,
    'bRegex_28',
    'bSearchable_28',
    'sSearch_29' => false,
    'bRegex_29',
    'bSearchable_29',
    'sSearch_30' => false,
    'bRegex_30',
    'bSearchable_30',
    'sSearch_31' => false,
    'bRegex_31',
    'bSearchable_31',
    'sSearch_32' => false,
    'bRegex_32',
    'bSearchable_32',
    'sSearch_33' => false,
    'bRegex_33',
    'bSearchable_33',
    'sSearch_34' => false,
    'bRegex_34',
    'bSearchable_34',
    'sSearch_35' => false,
    'bRegex_35',
    'bSearchable_35',
    'sSearch_36' => false,
    'bRegex_36',
    'bSearchable_36',
    'sSearch_37' => false,
    'bRegex_37',
    'bSearchable_37',
    'sSearch_38' => false,
    'bRegex_38',
    'bSearchable_38',
    'sSearch_39' => false,
    'bRegex_39',
    'bSearchable_39',
    'sSearch_40' => false,
    'bRegex_40',
    'bSearchable_40',
    'sSearch_41' => false,
    'bRegex_41',
    'bSearchable_41',
    'sSearch_42' => false,
    'bRegex_42',
    'bSearchable_42',
    'sSearch_43' => false,
    'bRegex_43',
    'bSearchable_43',
    'sSearch_44' => false,
    'bRegex_44',
    'bSearchable_44',
    'sSearch_45' => false,
    'bRegex_45',
    'bSearchable_45',
    'sSearch_46' => false,
    'bRegex_46',
    'bSearchable_46',
    'sSearch_47' => false,
    'bRegex_47',
    'bSearchable_47',
    'sSearch_48',
    'bRegex_48',
    'bSearchable_48',
    'sSearch_49' => false,
    'bRegex_49',
    'bSearchable_49',
    'sSortDir_0',
    'iSortingCols',
    'bSortable_0',
    'bSortable_1',
    'bSortable_2',
    'bSortable_3',
    'bSortable_4',
    'bSortable_5',
    'bSortable_6',
    'bSortable_7',
    'bSortable_8',
    'bSortable_9',
    'bSortable_10',
    'bSortable_11',
    'bSortable_12',
    'bSortable_13',
    'bSortable_14',
    'bSortable_15',
    'bSortable_16',
    'bSortable_17',
    'bSortable_18',
    'bSortable_19',
    'bSortable_20',
    'bSortable_21',
    'bSortable_22',
    'bSortable_23',
    'bSortable_24',
    'bSortable_25',
    'bSortable_26',
    'bSortable_27',
    'bSortable_28',
    'bSortable_29',
    'bSortable_30',
    'bSortable_31',
    'bSortable_32',
    'bSortable_33',
    'bSortable_34',
    'bSortable_35',
    'bSortable_36',
    'bSortable_37',
    'bSortable_38',
    'bSortable_39',
    'bSortable_40',
    'bSortable_41',
    'bSortable_42',
    'bSortable_43',
    'bSortable_44',
    'bSortable_45',
    'bSortable_46',
    'bSortable_47',
    'bSortable_48',
    'bSortable_49',
    'minarea',
    'maxarea',
    'minprice',
    'maxprice',
    'dateaddedS',
    'dateupdatedS',
    'dateaddedSto',
    'dateupdatedSto',
    'name_ar',
    'status',*/
];