INSERT INTO `contact_source` (`source`) VALUES
( '7 days'),
( 'Abu Dhabi week'),
( 'abudhabi.classonet.com'),
( 'Agent'),
( 'Agent External'),
( 'Agent Internal'),
( 'Al Ayam'),
( 'Al Bayan'),
( 'Al Futtaim'),
( 'Al Ittihad News paper'),
( 'Al Khaleej'),
( 'Al Rai'),
( 'AL Watan'),
( 'Arab Times'),
( 'Asharq Al Awsat'),
( 'Bank Referral'),
( 'Bayut.com'),
( 'Blackberry SMS'),
( 'Business Card'),
( 'Client referral'),
( 'Cold Call'),
( 'Colours TV'),
( 'Company Email'),
( 'Database'),
( 'Developer'),
( 'Direct Call'),
( 'Direct Client'),
( 'Drive around'),
( 'Dubizzle Feature'),
( 'Dubizzle.com'),
( 'Dzooom.com'),
( 'Email campaign'),
( 'Ertebat'),
( 'Exhibition Stand'),
( 'Existing client'),
( 'EzEstate'),
( 'EzHeights.com'),
( 'Facebook'),
( 'Flyers'),
( 'Forbes Mailer'),
( 'Friend or Relative'),
( 'Google'),
( 'Gulf Daily News'),
( 'Gulf News'),
( 'Gulf News Mailer'),
( 'Gulf Newspaper Freehold'),
( 'Gulf Newspaper Residential'),
( 'Gulf Times'),
( 'Gulfnews Freehold'),
( 'Gulfpropertyportal.com'),
( 'Hut.ae'),
( 'Instagram'),
( 'JustProperty.com'),
( 'JustRentals.com'),
( 'JUWAI'),
( 'Khaleej Times'),
( 'LinkedIn'),
( 'Listanza'),
( 'Live Chat'),
( 'Locanto'),
( 'lookup.ae'),
( 'Luxury Square Foot'),
( 'LuxuryEstate.com'),
( 'Magazine'),
( 'Memaar TV'),
( 'MoneyCamel.com'),
( 'National News paper'),
( 'Newsletter'),
( 'Newspaper advert'),
( 'Not Specified'),
( 'Oforo.com'),
( 'Old Landlord'),
( 'Online Banners'),
( 'Open House'),
( 'Open House Flyer'),
( 'Other'),
( 'Other portal'),
( 'Outdoor Media'),
( 'Personal Referral'),
( 'Property Acquisition Department'),
( 'Property Finder Premium'),
( 'Property Inc.'),
( 'Property life'),
( 'Property Management'),
( 'Property Trader'),
( 'Property Weekly'),
( 'Propertyfinder.ae'),
( 'Propertyonline'),
( 'Propertywifi.com'),
( 'PropSpace MLS'),
( 'Radio'),
( 'Radio Advert'),
( 'Referral within company'),
( 'Relocation'),
( 'rezora.com'),
( 'Rightmove.co.uk'),
( 'Roadshow'),
( 'Sandcastles.ae'),
( 'School Communicator'),
( 'Search Engine'),
( 'Signboard'),
( 'SMS campaign'),
( 'Social media Campaign'),
( 'Souq.com'),
( 'Staff Mailer'),
( 'Twitter'),
( 'Walk-in'),
( 'Wasset.net'),
( 'Website'),
( 'Whatpricemyhome'),
( 'Whatsapp'),
( 'Word of Mouth'),
( 'www.propertyportal.ae'),
( 'Youtube'),
( 'Yzer.com'),
( 'Zawya Mailer'),
( 'Zoopla')
