INSERT INTO `features` (`features`) VALUES
( 'Balcony'),
( 'Basement parking'),
( 'BBQ area'),
( 'Broadband ready'),
( 'Built in wardrobes'),
( 'Carpets'),
( 'Central air conditioning'),
( 'Central heating'),
( 'Community View'),
( 'Covered parking'),
( 'Driver\'s Room'),
( 'Fully fitted kitchen'),
( 'Fully furnished'),
( 'Gazebo and outdoor entertaining area'),
( 'Gymnasium'),
( 'Intercom'),
( 'Jacuzzi'),
( 'Kitchen white goods'),
( 'Maid\'s room'),
( 'Marble floors'),
( 'On high floor'),
( 'On mid floor'),
( 'Part furnished'),
( 'Pets allowed'),
( 'Private garage'),
( 'Private garden'),
( 'Private swimming pool'),
( 'Professionally landscaped garden'),
( 'Sauna'),
( 'Shared swimming pool'),
( 'Solid wood floors'),
( 'Steam room'),
( 'Study'),
( 'Upgraded interior'),
( 'View of gardens'),
( 'View of golf course'),
( 'View of parkland'),
( 'View of sea/water'),
( '24 hours Maintenance'),
( 'Bank/ATM Facility'),
( 'Basketball Court'),
( 'Beach Access'),
( 'Bus services'),
( 'Business Center'),
( 'Children\'s nursery'),
( 'Children\'s play area'),
( 'Clubhouse'),
( 'Communal gardens'),
( 'Concierge service'),
( 'Cycling tracks'),
( 'Fitness Center'),
( 'Golf club and clubhouse'),
( 'Laundry Service'),
( 'Marina Berth'),
( 'Metro station'),
( 'Mosque'),
( 'Polo club and clubhouse'),
( 'Public park'),
( 'Public parking'),
( 'Public transport'),
( 'Recreational Facilities'),
( 'Restaurants'),
( 'School'),
( 'Shopping mall'),
( 'Shops'),
( 'Sports academies'),
( 'Squash courts'),
( 'Tennis courts'),
( 'Valet Service'),
( 'Walking Trails')
