INSERT INTO `religion` (`religions`) VALUES
('Christianity'),
('Islam'),
('Secular/Nonreligious/Agnostic/Atheist'),
('Hinduism'),
('Chinese traditional religion'),
('Buddhism'),
('primal-indigenous'),
('African Traditional & Diasporic'),
('Sikhism'),
('Juche'),
('Jainism'),
('Shinto'),
('Cao Dai'),
('Zoroastrianism'),
('Tenrikyo'),
('Neo-Paganism'),
('Unitarian-Universalism'),
('Rastafarianism'),
('Scientology'),
('Russian Orthodox'),
('Greek Orthodox')