<?php
/**
 * Created by PhpStorm.
 * User: qp
 * Date: 05.02.2018
 * Time: 12:19
 */

return [
    'iColumns' => 45,
    'sColumns',
    'iDisplayStart' => 0,
    'iDisplayLength' => 5000,
    'mDataProp_0' => 0,
    'mDataProp_1' => 1,
    'mDataProp_2' => 2,
    'mDataProp_3' => 3,
    'mDataProp_4' => 4,
    'mDataProp_5' => 5,
    'mDataProp_6' => 6,
    'mDataProp_7' => 7,
    'mDataProp_8' => 8,
    'mDataProp_9' => 9,
    'mDataProp_10' => 10,
    'mDataProp_11' => 11,
    'mDataProp_12' => 12,
    'mDataProp_13' => 13,
    'mDataProp_14' => 14,
    'mDataProp_15' => 15,
    'mDataProp_16' => 16,
    'mDataProp_17' => 17,
    'mDataProp_18' => 18,
    'mDataProp_19' => 19,
    'mDataProp_20' => 20,
    'mDataProp_21' => 21,
    'mDataProp_22' => 22,
    'mDataProp_23' => 23,
    'mDataProp_24' => 24,
    'mDataProp_25' => 25,
    'mDataProp_26' => 26,
    'mDataProp_27' => 27,
    'mDataProp_28' => 28,
    'mDataProp_29' => 29,
    'mDataProp_30' => 30,
    'mDataProp_31' => 31,
    'mDataProp_32' => 32,
    'mDataProp_33' => 33,
    'mDataProp_34' => 34,
    'mDataProp_35' => 35,
    'mDataProp_36' => 36,
    'mDataProp_37' => 37,
    'mDataProp_38' => 38,
    'mDataProp_39' => 39,
    'mDataProp_40' => 40,
    'mDataProp_41' => 41,
    'mDataProp_42' => 42,
    'mDataProp_43' => 43,
    'mDataProp_44' => 44,
    'sSearch',
    'bRegex' => false,
    'sSearch_0',
    'bRegex_0' => false,
    'bSearchable_0' => true,
    'sSearch_1',
    'bRegex_1' => false,
    'bSearchable_1' => true,
    'sSearch_2',
    'bRegex_2' => false,
    'bSearchable_2' => true,
    'sSearch_3',
    'bRegex_3' => false,
    'bSearchable_3' => true,
    'sSearch_4',
    'bRegex_4' => false,
    'bSearchable_4' => true,
    'sSearch_5',
    'bRegex_5' => false,
    'bSearchable_5' => true,
    'sSearch_6',
    'bRegex_6' => false,
    'bSearchable_6' => true,
    'sSearch_7',
    'bRegex_7' => false,
    'bSearchable_7' => true,
    'sSearch_8',
    'bRegex_8' => false,
    'bSearchable_8' => true,
    'sSearch_9',
    'bRegex_9' => false,
    'bSearchable_9' => true,
    'sSearch_10',
    'bRegex_10' => false,
    'bSearchable_10' => true,
    'sSearch_11',
    'bRegex_11' => false,
    'bSearchable_11' => true,
    'sSearch_12',
    'bRegex_12' => false,
    'bSearchable_12' => true,
    'sSearch_13',
    'bRegex_13' => false,
    'bSearchable_13' => true,
    'sSearch_14',
    'bRegex_14' => false,
    'bSearchable_14' => true,
    'sSearch_15',
    'bRegex_15' => false,
    'bSearchable_15' => true,
    'sSearch_16',
    'bRegex_16' => false,
    'bSearchable_16' => true,
    'sSearch_17',
    'bRegex_17' => false,
    'bSearchable_17' => true,
    'sSearch_18',
    'bRegex_18' => false,
    'bSearchable_18' => true,
    'sSearch_19',
    'bRegex_19' => false,
    'bSearchable_19' => true,
    'sSearch_20',
    'bRegex_20' => false,
    'bSearchable_20' => true,
    'sSearch_21',
    'bRegex_21' => false,
    'bSearchable_21' => true,
    'sSearch_22',
    'bRegex_22' => false,
    'bSearchable_22' => true,
    'sSearch_23',
    'bRegex_23' => false,
    'bSearchable_23' => true,
    'sSearch_24',
    'bRegex_24' => false,
    'bSearchable_24' => true,
    'sSearch_25',
    'bRegex_25' => false,
    'bSearchable_25' => true,
    'sSearch_26',
    'bRegex_26' => false,
    'bSearchable_26' => true,
    'sSearch_27',
    'bRegex_27' => false,
    'bSearchable_27' => true,
    'sSearch_28',
    'bRegex_28' => false,
    'bSearchable_28' => true,
    'sSearch_29',
    'bRegex_29' => false,
    'bSearchable_29' => true,
    'sSearch_30',
    'bRegex_30' => false,
    'bSearchable_30' => true,
    'sSearch_31',
    'bRegex_31' => false,
    'bSearchable_31' => true,
    'sSearch_32',
    'bRegex_32' => false,
    'bSearchable_32' => true,
    'sSearch_33',
    'bRegex_33' => false,
    'bSearchable_33' => true,
    'sSearch_34',
    'bRegex_34' => false,
    'bSearchable_34' => true,
    'sSearch_35',
    'bRegex_35' => false,
    'bSearchable_35' => true,
    'sSearch_36',
    'bRegex_36' => false,
    'bSearchable_36' => true,
    'sSearch_37',
    'bRegex_37' => false,
    'bSearchable_37' => true,
    'sSearch_38',
    'bRegex_38' => false,
    'bSearchable_38' => true,
    'sSearch_39',
    'bRegex_39' => false,
    'bSearchable_39' => true,
    'sSearch_40',
    'bRegex_40' => false,
    'bSearchable_40' => true,
    'sSearch_41',
    'bRegex_41' => false,
    'bSearchable_41' => true,
    'sSearch_42',
    'bRegex_42' => false,
    'bSearchable_42' => true,
    'sSearch_43',
    'bRegex_43' => false,
    'bSearchable_43' => true,
    'sSearch_44',
    'bRegex_44' => false,
    'bSearchable_44' => true,
    'iSortCol_0' => 32,
    'sSortDir_0' => 'desc',
    'iSortingCols' => 1,
    'bSortable_0' => false,
    'bSortable_1' => true,
    'bSortable_2' => true,
    'bSortable_3' => true,
    'bSortable_4' => true,
    'bSortable_5' => true,
    'bSortable_6' => true,
    'bSortable_7' => true,
    'bSortable_8' => true,
    'bSortable_9' => true,
    'bSortable_10' => true,
    'bSortable_11' => true,
    'bSortable_12' => true,
    'bSortable_13' => true,
    'bSortable_14' => true,
    'bSortable_15' => true,
    'bSortable_16' => true,
    'bSortable_17' => true,
    'bSortable_18' => true,
    'bSortable_19' => true,
    'bSortable_20' => true,
    'bSortable_21' => true,
    'bSortable_22' => true,
    'bSortable_23' => true,
    'bSortable_24' => true,
    'bSortable_25' => true,
    'bSortable_26' => true,
    'bSortable_27' => true,
    'bSortable_28' => true,
    'bSortable_29' => true,
    'bSortable_30' => true,
    'bSortable_31' => true,
    'bSortable_32' => true,
    'bSortable_33' => true,
    'bSortable_34' => true,
    'bSortable_35' => true,
    'bSortable_36' => true,
    'bSortable_37' => true,
    'bSortable_38' => true,
    'bSortable_39' => true,
    'bSortable_40' => true,
    'bSortable_41' => true,
    'bSortable_42' => true,
    'bSortable_43' => true,
    'bSortable_44' => true,
    'as_category_id',
    'as_min_beds' => 0,
    'as_max_beds' => 0,
    'as_unit',
    'as_enquired_for_referance',
    'as_min_price',
    'as_max_price',
    'as_min_area',
    'as_max_area',
    'as_date_enq_to',
    'as_date_enq_from',
    'as_created_by' => 0,
    'as_financial_situation',
    'escalated',
    'leads_datatype_tab',
    'dateupdatedSto',
    'dateupdatedSfrom',
    'dateenquirySto',
    'dateenquirySfrom',
    'landlord_id',
    'listings_id',
    'deals_id',
    'contracts_id',
    'type',
];